### PR TITLE
price-feed-bot-Manav2808

### PR DESCRIPTION
**Pull request by 0xRadioAc7iv**

### CODE REVIEW

**Comment by Lucifer0x17** [comment]
Hey Manav, You are doing great.. that's a good progress. 

Please provide the answers to following confusions:

- However, I can't see your process ID where i can do the request. 
- both handlers have same names so they will override itself.
- Your bot is not returning the price to the process from which the request has been generated.

Let me know if you need anything. Ping me in the discord channel for faster comunication.

**Comment by Manav2808** [comment]
Hey @Lucifer0x17, I have added the Process ID and removed one of the handlers as it was redundant. The bot returns the price but for some reason, it takes a long time to send it.

**Comment by Lucifer0x17** [comment]
Hey @Manav2808 I tried the request haven't received any response.
Can you tell me if there is something is wrong??

image

**Comment by Manav2808** [comment]
Hey @Lucifer0x17, I looked into it and found out that the response is always returned to MY process even if i call the Send() function from another process. I also looked for ways but could not figure out how to send the response data to the process which calls the Send() method.

**Comment by Lucifer0x17** [comment]
Hey @Manav2808 , that is happening because you are not sending the response. You need to create a handler for 0rbit process to catch the price feed and send it back to the process which requested for the price feed. :)

**Comment by Manav2808** [comment]
I have added a REQUESTS table which will contain a list of Processes that send the Price Feed Requests, then as soon as the Price Feed is Recieved, it is sent back to them, then the Process ID is removed from the table, also it's taking too long to receive the Price Feed, so it's not there in the Screenshot. But it should work.

**Comment by Lucifer0x17** [comment]
@Manav2808 Thanks for the update manav. Looking into it. Also, some issues are going on with 0rbit will get back soon

**Comment by Manav2808** [comment]
Wallet Address: o_v14eOPw02330fnpRzw9_CWDZaKsWHoQ1aXyTrdjkE

**Comment by Lucifer0x17** [comment]
Done

**Pull request closed without merging**
